flowchart LR
  A[Conclusiones:]
  A --> B["Necesidad de automatización: La implementación de un sistema automatizado minimiza errores humanos, acelera la asignación de cargas académicas y facilita el acceso a recursos institucionales, alineándose con las necesidades reales de los usuarios."]
  B --> C["Selección de metodología ágil: Scrum se elige por su estructura iterativa, la comunicación constante con los stakeholders y la capacidad de adaptarse rápidamente a cambios en los requisitos."]
  A -->D["Arquitectura de software: Una Screaming Architecture basada en capas desacopladas y patrones de diseño (Singleton, Builder, Result) asegura escalabilidad, mantenibilidad y facilidad de evolución del sistema."]
  D --> E["Impacto de la solución: La aplicación mejora la eficiencia operativa, refuerza la transparencia en los procesos y proporciona datos confiables para la toma de decisiones estratégicas."]

