flowchart TB

    E[Enfoque de la investigación]
    L[Nivel de la investigación]
    D[Diseño de la investigación]

    E --> EQ["Cuantitativo<br/>(Uso de métodos de cálculos numéricos para validar hipótesis)"]
    E --> PP["Paradigma positivista<br/>(“Desarrollar preguntas e hipótesis antes, durante o después de la recolección y el análisis de los datos.”)"]
    E --> OB["Objetividad<br/>(Enfoque en hechos observables y cuantificables)"]
    E --> VH["Validación de hipótesis<br/>(Intención de validar hipótesis mediante datos)"]
    E --> RR["Rigurosidad y replicabilidad<br/>(Estructuración rigurosa, ordenada y sistemática para resultados fiables y replicables)"]

    L --> Des["Descriptivo<br/>(Especifica propiedades, características y perfiles sin explorar relaciones)"]
    L --> EP["Especificar propiedades y características<br/>(Medir o recoger información de manera independiente o conjunta)"]
    L --> CP["Caracterización de procesos actuales<br/>(Para diseñar la aplicación web según requerimientos de la organización)"]

    D --> NE["No experimental<br/>(Sin manipulación de variables)"]
    D --> TR["Transversal<br/>(Datos recolectados una sola vez)"]
    D --> CF["De campo<br/>(Recolección en el entorno real de la muestra)"]
    D --> DU["Única recolección de datos<br/>(Datos obtenidos en un solo momento)"]
