flowchart TB
    PM[Población y muestra]

    PM --> P[Población]
    PM --> S[Muestra]
    PM --> D[Decisión de no usar muestra]
    PM --> E[Efecto]

    P --> PD["Definición:<br/>“conjunto de individuos ... elementos (...) que participan del fenómeno ...”<br/>(Neftali, 2016)"]
    P --> PO["Población objetivo:<br/>Personal administrativo de la planta docente de Software de la UNIB.E"]

    S --> SD["Definición:<br/>“subgrupo de la población o universo ...”<br/>(Neftali, 2016)"]
    S --> ST["Selección depende del tamaño de la población"]

    D --> DA["“Si la población, por el número de unidades que la integran, resulta accesible en su totalidad, no será necesario extraer una muestra.”<br/>(Arias, 2012)"]
    D --> DJ["Decisión:<br/>recolectar datos de toda la población"]

    E --> EF["Los datos recopilados serán de todos los involucrados en la recolección."]
