flowchart TD
  
  B["Tipo de arquitectura: API RESTful (Cliente-Servidor desacoplado)"]
  B --> B1["Frontend: Angular"]
  B --> B2["Backend: Laravel"]
  B --> B3["Base de datos: MySQL"]
  
  C["Principios adoptados"]
  C --> C1["Escalabilidad"]
  C --> C2["Mantenibilidad"]
  C --> C3["Reutilización de componentes"]
  C --> C4["Separación de responsabilidades"]
  
  D["Patrones de diseño"]
  D --> D1["Singleton"]
  D --> D2["Builder"]
  D --> D3["Result Pattern"]
  